// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace teste_ses_completo.SVS.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("cadastrar")]
    [NUnit.Framework.CategoryAttribute("cadastro")]
    public partial class CadastrarFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CadastrarUsuario.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "cadastrar", "\tComo usuario do sistema\r\n\tEu quero me registrar\r\n\tPara que eu possa acessar o si" +
                    "stema", ProgrammingLanguage.CSharp, new string[] {
                        "cadastro"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cadastrar Ususario")]
        [NUnit.Framework.CategoryAttribute("cadastrar_usuario")]
        [NUnit.Framework.TestCaseAttribute("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
            "aaaaaaaaaaaaaaaaaaa", "aaaa@mailinator.com", "04/10/1992", "35545884-6", "4199929-6311", "Rua Catarina Basso Brunetti", "11111", "Ribeirao Lipa", "Q.04", "78048135", "Mato Grosso", "Chapada dos Guimarães", "212.236.079-84", "1234567", "1234567", null)]
        [NUnit.Framework.TestCaseAttribute("1111111", "cadastrarusuarioses@mailinator.com", "05/02/2004", "48093928-7", "999999999", "Rua Minas Gerais", "13", "Centro", "Q01", "46203970", "Bahia", "Alegre", "869.526.555-22", "1234", "1234", null)]
        [NUnit.Framework.TestCaseAttribute("Igor Heitor Almeida", "1111111111111111111111111111111111111", "20/11/1991", "29128046-8", "81995134846", "Rua Cecília Lima de Santana", "11", "Centro", "A3", "53620857", "Pernambuco", "Igarassu", "201.739.024-05", "OJNcJXNeUP1", "OJNcJXNeUP1", null)]
        [NUnit.Framework.TestCaseAttribute("Rafaela Letícia Costa", "aaaaaaaaaaaaaaaaaaaa@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com", "21/12/1964", "32479461-7", "41984874506", "Rua Augusto Zibarth", "22", "Centro", "xse", "81560360", "Paraná", "Curitiba", "143.339.199-67", "123456", "123456", null)]
        [NUnit.Framework.TestCaseAttribute("Anthony Otávio Almeida", "antony@mailinator.com", "14/0a/1991", "15357457-4", "44994090543", "Rua do Engenheiro", "100", "Viviani", "Condominio 1", "87203166", "Paraná", "Cianorte", "645.653.689-86", "8abc7203", "8abc7203", null)]
        [NUnit.Framework.TestCaseAttribute("Rafaela Catarina Sabrina Costa", "rafaela@mailinator.com", "15/10/19999", "22167511-5", "41989086361", "Rua Wadih Riskala", "1000", "Centro", "Cond", "78048135", "Paraná", "Curitiba", "779.303.389-24", "1234", "1234", null)]
        [NUnit.Framework.TestCaseAttribute("Maria Isabelle Barros", "isabelle@mailinator.com", "08/06/1991", "40402209-a", "92983146026", "Beco Maria Ferreira Lopes", "213", "Beco", "FA", "69027001", "Amazonas", "Manaus", "929.680.042-04", "Manaus", "Manaus", null)]
        [NUnit.Framework.TestCaseAttribute("Beatriz Heloisa Souza", "beatriz@mailinator.com", "07/03/1998", "48245377-11", "995134846", "Rua Augusto Zibarth", "200", "Vila Helena", "xz", "82700510", "Espírito Santo", "Vitória", "448.160.409-35", "santo", "santo", null)]
        [NUnit.Framework.TestCaseAttribute("Maitê Emily Lima", "maite@mailinator.com", "11/03/1953", "31372468-4", "aaaaaaaaaaaa", "Rua Cândido Cardoso Mendonça", "174", "Engenho", "i", "23820150", "Rio de Janeiro", "Rio de Janeiro", "240.104.227-00", "engenho1", "engenho1", null)]
        [NUnit.Framework.TestCaseAttribute("Maitê Eloá Dias", "eloa@mailinator.com", "15/10/1999", "34282753-4", "111111111111111", "Rua São Manoel", "90", "Centro", "zx", "83503150", "Amazonas", "Manaus", "403.333.809-83", "1234567", "1234567", null)]
        [NUnit.Framework.TestCaseAttribute("Sarah Yasmin Bruna Lima", "sarah@mailinator.com", "07/02/1953", "25298072-4", "86996636203", "11111111111111111111111", "11", "Areias", "xxx", "64027634", "Piauí", "Teresina", "026.797.523-68", "teresina1", "teresina1", null)]
        [NUnit.Framework.TestCaseAttribute("André Ricardo Erick Dias", "andre@mailinator.com", "19/07/1947", "36536104-5", "4128608950", "11111111111111111111111111111111", "13", "Vila Tibério", "zzzz", "81260432", "São Paulo", "Ribeirão Preto", "217.678.199-60", "1234", "1234", null)]
        [NUnit.Framework.TestCaseAttribute("Cauã Luan Campos", "caua@mailinator.com", "03/10/1953", "42845803-8", "8698942-2253", "Rua Bandeirantes", "aaa", "Boa Esperança", "@#$", "64215670", "Piauí", "Parnaiba", "839.916.913-70", "parnaiba1", "parnaiba1", null)]
        [NUnit.Framework.TestCaseAttribute("Rayssa Sarah Almeida", "rayssa@mailinator.com", "16/07/1947", "12841303-7", "4598480-5723", "Rua Arnaldo Aldino Dullius", "11111111111", "Diadema", "sae", "85905544", "Bahia", "Baianópolis", "310.884.115-76", "12345", "12345", null)]
        [NUnit.Framework.TestCaseAttribute("Diogo Renan Luiz dos Santos", "diogo@mailinator.com", "06/02/1953", "11584564-1", "65988918167", "Rua dos Papagaios", "810", "Lixeira", "11111111111111111111111111111111", "78075864", "Mato Grosso", "Cuiabá", "049.805.591-40", "cuiaba3", "cuiaba3", null)]
        [NUnit.Framework.TestCaseAttribute("Joana Manuela Cavalcanti", "joana@mailinator.com", "05/11/2011", "13868476-5", "7793951546", "Avenida Antônio Carlos Magalhães", "18", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "sxd", "47830970", "Rio de Janeiro", "Niterói", "207.279.725-02", "nit123", "nit123", null)]
        [NUnit.Framework.TestCaseAttribute("Marcela Olivia Cavalcanti", "marcela@mailinator.com", "06/03/1977", "18874130-6", "4899140-9053", "Rua Professora Maria de Lourdes Cechimel", "12", "1111111111", "Margem esquerda", "88708522", "Santa Catarina", "Tubarão", "943.464.199-33", "tubarao1", "tubarao1", null)]
        [NUnit.Framework.TestCaseAttribute("Gabrielly Beatriz dos Santos", "gabi@mailinator.com", "02/11/1947", "47422265-2", "77983720125", "Avenida Antônio Carlos Magalhães", "20", "Centro", "asc", "1111111111", "São Paulo", "Limeira", "391.963.335-02", "limeira1", "limeira1", null)]
        [NUnit.Framework.TestCaseAttribute("Emanuelly Yasmin Rafaela Barbosa", "emanu@mailinator.com", "03/01/1977", "18460635-4", "12983487395", "Rua Albino Raimundo Nunes", "1000", "Centro", "X1", "1231658a", "São Paulo", "Jacareí", "422.426.258-45", "jacarei1", "jacarei1", null)]
        [NUnit.Framework.TestCaseAttribute("Betina Nina Almeida", "betina@mailinator.com", "16/07/1947", "49046384-8", "77985298303", "Avenida Antônio Carlos Magalhães", "13", "Boa Esperança", "aqe", "47830970", "Paraná", "Londrina", "417.484.3851-65", "londrina1", "londrina1", null)]
        [NUnit.Framework.TestCaseAttribute("Elias Lorenzo Pereira", "elias@mailinator.com", "20/10/1985", "38769754-8", "63998691146", "Quadra 108 Sul", "14", "Projetado", "Alameda", "77020118", "Tocantiss", "Palmas", "606.837.971-07", "palmas1", "palmas1", null)]
        [NUnit.Framework.TestCaseAttribute("Bruno Francisco Filipe Ribeiro", "bruno@mailinator.com", "26/09/1991", "39355365-6", "98983633689", "Rua Renato Viana", "24", "Nova Viana", "Q07", "65036000", "Maranhão", "São Luíss", "607.853.713-03", "luis1", "luis1", null)]
        [NUnit.Framework.TestCaseAttribute("Carlos Eduardo Felipe Fernandes", "carlos@mailinator.com", "07/03/1980", "23636698-1", "27989294298", "Rua A", "255", "Retiro Saudoso", "xwyz", "29154855", "Espírito Santo", "Cariacica", "980.728.267-5a", "caca1", "caca1", null)]
        [NUnit.Framework.TestCaseAttribute("Lucas Renato Oliveira", "lucas@mailinator.com", "19/06/1962", "18231999-4", "988383463", "Quadra 10", "33", "centro", "Conjunto H", "73368596", "Distrito Federal", "Brasilia", "062.427.551-57", "aaaaaaaaaaa", "aaaaaaaaaaa", null)]
        [NUnit.Framework.TestCaseAttribute("Maria Eduarda Costa", "maria@mailinator.com", "05/05/1954", "29666085-1", "68993752804", "Rua F", "1000", "Loteamento Santa Helena", "xzw", "69908752", "Acre", "Rio Branco", "527.896.442-17", "branco1", "branco2", null)]
        [NUnit.Framework.TestCaseAttribute("Mariane Bruna Lívia da Silva", "mariane@mailinator.com", "08/10/1947", "32953956-5", "77994351025", "Avenida Antônio Carlos Magalhães", "210", "Centro", "sxc", "47830970", "Sergipe", "Aracajú", "942.753.555-55", "111111111111a", "111111111111a", null)]
        [NUnit.Framework.TestCaseAttribute("Julio Renato Antonio Cardoso", "julio@mailinator.com", "20/05/1995", "44.915.956-5", "98615-6122", "Rua Tapajós", "510", "Atalaia", "xyz", "67013-542", "Pará", "Ananindeua", "749.163.710-89", "cadastro1", "cadastro1", null)]
        [NUnit.Framework.TestCaseAttribute("Tester Tester", "tester@mailinator.com", "06/12/1977", "29666085-7", "66999666917", "Rua Um", "11", "Centro", "Q05", "78048135", "Mato Grosso do Sul", "Água Boa", "305.806.588-48", "123456", "123456", null)]
        public virtual void CadastrarUsusario(
                    string nome, 
                    string email, 
                    string nascimento, 
                    string rg, 
                    string celular, 
                    string logradouro, 
                    string numero, 
                    string bairro, 
                    string complemento, 
                    string cep, 
                    string uf, 
                    string municipio, 
                    string cpf, 
                    string senha, 
                    string repetir, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "cadastrar_usuario"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar Ususario", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("que estou na pagina de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And(string.Format("eu preencho o campo nome {0}", nome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("eu preencho o campo email {0}", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("eu preencho o campo nascimento {0}", nascimento), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("eu preencho o campo rg {0}", rg), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And(string.Format("eu preencho o campo celular{0}", celular), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And(string.Format("eu preencho o campo logradouro{0}", logradouro), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And(string.Format("eu preencho o campo numero{0}", numero), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And(string.Format("eu preencho o campo bairro{0}", bairro), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And(string.Format("eu preencho o campo complemento{0}", complemento), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And(string.Format("eu preencho o campo cep{0}", cep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And(string.Format("eu preencho o campo uf {0}", uf), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And(string.Format("eu preencho o campo municipio {0}", municipio), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And(string.Format("eu preencho o campo cpf{0}", cpf), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And(string.Format("eu preencho o campo senha {0}", senha), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And(string.Format("eu preencho o campo repetir {0}", repetir), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("eu aceito o Termo de uso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("eu clico no botao Entrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
